- Gemfile
- Gemfile.lock
- app/models/booking.rb
- app/models/course.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20200224153343_devise_create_users.rb
- db/migrate/20200224154144_add_description_to_users.rb
- db/migrate/20200224154823_create_courses.rb
- db/migrate/20200224155242_create_bookings.rb
- db/migrate/20200224162218_add_name_to_users.rb
- db/schema.rb
- test/models/booking_test.rb
- test/models/course_test.rb
- test/models/user_test.rb
Added the Devise (User Model)
Added the Courses Model
Added the Bookings Model
> added models and authentications

- config/routes.rb
> added all routes

- Gemfile
- Gemfile.lock
- app/controllers/courses_controller.rb
- app/controllers/users_controller.rb
- app/models/course.rb
- app/models/user.rb
- app/views/courses/index.html.erb
- db/migrate/20200224175517_add_name_to_courses.rb
- db/migrate/20200225103453_add_user_to_courses.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/courses_controller_test.rb
- test/controllers/users_controller_test.rb
Added controllers and database, and max is a lil bitch
> Controllers

- app/controllers/application_controller.rb
- app/views/courses/new.html.erb
- app/views/users/confirmations/new.html.erb
- app/views/users/mailer/confirmation_instructions.html.erb
- app/views/users/mailer/email_changed.html.erb
- app/views/users/mailer/password_change.html.erb
- app/views/users/mailer/reset_password_instructions.html.erb
- app/views/users/mailer/unlock_instructions.html.erb
- app/views/users/passwords/edit.html.erb
- app/views/users/passwords/new.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/shared/_error_messages.html.erb
- app/views/users/shared/_links.html.erb
- app/views/users/unlocks/new.html.erb
- config/initializers/devise.rb
- db/migrate/20200224154144_add_description_to_users.rb
- db/migrate/20200224162218_add_name_to_users.rb
- db/schema.rb
Log in Done
Added a view (new) for courses
> Log in ready + new.html.erb for courses

- app/controllers/application_controller.rb
- app/controllers/courses_controller.rb
Added the ability to create a new account and add a new course once logged in
> added sign-up functionality and ability to add a new course

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/views/courses/index.html.erb
Create courses view page, with map and courses cards
> course_view

- app/assets/stylesheets/components/_navbar.scss
- app/views/courses/home.html.erb
Added links with link_to to the navbar links REGISTER and Sign in 
Added also a bit of styling - check comments in show.html.erb line 17 and 22 and in css componets _navbar
> Added links and a bit of styling to navbar links - Register and SIGNIN

- app/assets/stylesheets/components/_navbar.scss
- app/views/courses/home.html.erb
Added link to invite a friend(to registration for now) and css
> Customize navbar

- app/assets/stylesheets/pages/_home.scss
- app/views/courses/home.html.erb
> Landingpage v2

- .gitignore
- app/controllers/courses_controller.rb
- app/views/courses/home.html.erb
- db/schema.rb
new front page -added iteration + new Home Controller
> New front page

- db/seeds.rb
> reseeded database

- db/seeds.rb
> fixed database

- config/puma.rb
> delete puma branch

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/show.html.erb
- config/routes.rb
> makes bio work

- app/models/course.rb
- app/views/courses/new.html.erb
- app/views/courses/show.html.erb
- db/migrate/20200227101531_add_subtitle_to_courses.rb
- db/migrate/20200227111836_change_city_from_courses.rb
- db/schema.rb
- db/seeds.rb
> finished our database

- app/controllers/courses_controller.rb
- app/views/courses/home.html.erb
- app/views/courses/index.html.erb
- db/migrate/20200227115919_add_picture_to_courses.rb
- db/migrate/20200227115957_add_avatar_to_users.rb
- db/schema.rb
- db/seeds.rb
> updated index

- app/views/layouts/application.html.erb
- db/schema.rb
> added link to profile page

- app/views/users/show.html.erb
> bookings now links to course page

- app/assets/stylesheets/components/_card.scss
- app/controllers/courses_controller.rb
- app/controllers/users_controller.rb
- app/views/courses/home.html.erb
- app/views/courses/index.html.erb
- app/views/courses/show.html.erb
- app/views/users/show.html.erb
- db/schema.rb
- db/seeds.rb
Added avatar iteration and city query
> added avatar and city query

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_user.scss
- app/views/courses/show.html.erb
> courses styling

- app/controllers/courses_controller.rb
- app/javascript/plugins/flatpickr.js
- app/models/course.rb
- app/views/courses/new.html.erb
- db/migrate/20200228102101_remove_date_from_bookings.rb
- db/migrate/20200228102406_add_start_to_courses.rb
- db/migrate/20200228102443_add_end_to_courses.rb
- db/schema.rb
- db/seeds.rb
> updated bookings

- app/controllers/courses_controller.rb
- app/views/courses/home.html.erb
- app/views/courses/index.html.erb
- app/views/courses/show.html.erb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
Added search funktion and avatar in user prof page
> Added search funktion and avatar in user prof page

- app/controllers/bookings_controller.rb
- app/views/users/show.html.erb
bookings now links to user page
> done with bookings

- db/seeds.rb
> seeds make sense now

- db/seeds.rb
> done with seeds
